name: antora docker images (build & deploy)
on:
  push:
    paths:
      - 'containers/antora/**'
      - '.github/workflows/workflow-antora.yml'
  workflow_dispatch:
jobs:
  build_and_push:
    name: Build and Push
    strategy:
      matrix:
        base_image: ["antora/antora"]
        base_image_version: [3.1.1, 3.1.4, 3.1.7]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Set current date as env variable
        run: echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%S%z')" >> $GITHUB_ENV
      - name: Build and push (${{github.ref_name == 'main'}})
        uses: docker/build-push-action@v5
        with:
          push: ${{github.ref_name == 'main'}}
          context: "{{defaultContext}}:containers/antora"
          tags: | 
            quay.io/bluebird/antora:${{matrix.base_image_version}}
            quay.io/bluebird/antora:${{matrix.base_image_version}}-b${{github.run_number}}
          build-args: |
            VERSION=${{matrix.base_image_version}}
            BASE_IMAGE=${{matrix.base_image}}
            BASE_IMAGE_VERSION=${{matrix.base_image_version}}
            BUILD_DATE=${{env.BUILD_DATE}}
            SOURCE=${{github.server_url}}/${{github.repository}}
            REVISION=${{github.sha}}
            BUILD_JOB_ID=${{github.run_id}}
            BUILD_NUMBER=${{github.run_number}}
            BUILD_URL=${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
            BUILD_BRANCH=${{github.ref}}
            VERSION=${{matrix.base_image_version}}